#include <iostream>
#include <fstream>
#include <string>
#include "SysYLexer.h"
#include "SysYParser.h"
#include "SysYFormatter.h"
#include "antlr4-runtime.h"

using namespace antlr4;


int main(int argc, const char* argv[]) {
    if (argc < 2) {
        std::cerr << "Usage: sysy_formatter <input-file>" << std::endl;
        return 1;
    }
    // TODO: You need to call the lexer and parser generated by ANTLR4,
    // and invoke the visit method in your own implemented Visitor.
    try {
        // 打开输入文件
        std::ifstream stream;
        stream.open(argv[1]);
        if (!stream.is_open()) {
            std::cerr << "Error: Cannot open file " << argv[1] << std::endl;
            return 1;
        }

        // 创建 ANTLR 输入流
        ANTLRInputStream input(stream);

        // 创建词法分析器
        SysYLexer lexer(&input);
        
        // 创建 token 流
        CommonTokenStream tokens(&lexer);
        
        // 创建语法分析器
        SysYParser parser(&tokens);

        // 获取语法分析树（从 compUnit 规则开始）
        tree::ParseTree* tree = parser.compUnit();

        // 创建 Visitor 对象并调用 visit 方法
        SysYFormatter formatter;
        std::string formatted = std::any_cast<std::string>(formatter.visit(tree));

        // 输出格式化后的代码
        std::cout << formatted;

    } catch (const std::exception& e) {
        std::cerr << "Error: " << e.what() << std::endl;
        return 1;
    }
    return 0;
}
